### ISSUE TITLE
Advanced Scheduling for Datadog Synthetics Non-Functional

### ISSUE THREAD

**Issue by elx-bob** [cloudposse/terraform-datadog-platform#100]
### Describe the Bug

Currently unable to set advanced Scheduling options for Datadog Synthetics. While I can easily set multiple Assertions on a single Synthetic Test, I am not able to set multiple Timeframes when attempting to create an advanced schedule for Synthetics.

### Expected Behavior

When passing multiple timeframes into the Synthetics module, multiple timeframes are expected to be set for the Synthetic Test.

### Steps to Reproduce

When passed into the Synthetics module, the below will set one Timeframe for the Synthetic Test.
```
  options:
    scheduling:
      timeframes:
        day: 1
        from: "07:00"
        to: "16:00"
      timezone: "America/New_York"
```

If you pass in multiple tiemframes, even though it is a valid YAML, the module errors out.
```
  options:
    scheduling:
      timeframes:
      - day: 1
        from: "07:00"
        to: "16:00"
      - day: 2
        from: "07:00"
        to: "16:00"
      timezone: "America/New_York"
```

### Screenshots

> ╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/datadog_synthetics/modules/synthetics/main.tf line 411, in resource "datadog_synthetics_test" "default":
│  411:               day  = timeframes.value.day
│     ├────────────────
│     │ timeframes.value is tuple with 2 elements
│ 
│ This value does not have any attributes.
╵
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/datadog_synthetics/modules/synthetics/main.tf line 412, in resource "datadog_synthetics_test" "default":
│  412:               from = timeframes.value.from
│     ├────────────────
│     │ timeframes.value is tuple with 2 elements
│ 
│ This value does not have any attributes.
╵
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/datadog_synthetics/modules/synthetics/main.tf line 413, in resource "datadog_synthetics_test" "default":
│  413:               to   = timeframes.value.to
│     ├────────────────
│     │ timeframes.value is tuple with 2 elements
│ 
│ This value does not have any attributes.
╵

### Additional Context

There also do not appear to be any examples of this functionality in the documentation or repository.
